// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Label_speed_screen_init(void)
{
    ui_Label_speed = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Label_speed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Label_speed);
    lv_img_set_src(ui_Image2, &ui_img_82773809);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Speed_Label = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_Speed_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speed_Label, -54);
    lv_obj_set_y(ui_Speed_Label, -60);
    lv_obj_set_align(ui_Speed_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed_Label, "Temp");
    lv_obj_set_style_text_color(ui_Speed_Label, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Speed_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelkmh1 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_Labelkmh1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelkmh1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelkmh1, -25);
    lv_obj_set_y(ui_Labelkmh1, 74);
    lv_obj_set_align(ui_Labelkmh1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelkmh1, "C");
    lv_obj_set_style_text_color(ui_Labelkmh1, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelkmh1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSPEDD = lv_slider_create(ui_Label_speed);
    lv_slider_set_value(ui_SliderSPEDD, 75, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSPEDD) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSPEDD, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSPEDD, 123);
    lv_obj_set_height(ui_SliderSPEDD, 244);
    lv_obj_set_x(ui_SliderSPEDD, -100);
    lv_obj_set_y(ui_SliderSPEDD, -1);
    lv_obj_set_align(ui_SliderSPEDD, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderSPEDD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSPEDD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSPEDD, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSPEDD, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderSPEDD, &ui_img_speed_slider_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSPEDD, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSPEDD, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderBAT = lv_slider_create(ui_Label_speed);
    lv_slider_set_value(ui_SliderBAT, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBAT) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBAT, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBAT, 106);
    lv_obj_set_height(ui_SliderBAT, 235);
    lv_obj_set_x(ui_SliderBAT, -147);
    lv_obj_set_y(ui_SliderBAT, 1);
    lv_obj_set_align(ui_SliderBAT, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderBAT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBAT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderBAT, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBAT, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderBAT, &ui_img_slider_battery_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderBAT, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBAT, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Percentlabel1 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_Percentlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Percentlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Percentlabel1, -172);
    lv_obj_set_y(ui_Percentlabel1, -90);
    lv_obj_set_align(ui_Percentlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Percentlabel1, "100%");
    lv_obj_set_style_text_color(ui_Percentlabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Percentlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Percentlabel1, &ui_font_MO16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Percentlbel2 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_Percentlbel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Percentlbel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Percentlbel2, -203);
    lv_obj_set_y(ui_Percentlbel2, -47);
    lv_obj_set_align(ui_Percentlbel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Percentlbel2, "75%");
    lv_obj_set_style_text_color(ui_Percentlbel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Percentlbel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Percentlbel2, &ui_font_MO16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PercentLabel3 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_PercentLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentLabel3, -219);
    lv_obj_set_y(ui_PercentLabel3, 7);
    lv_obj_set_align(ui_PercentLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PercentLabel3, "50%");
    lv_obj_set_style_text_color(ui_PercentLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PercentLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PercentLabel3, &ui_font_MO16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PercentLabel4 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_PercentLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentLabel4, -218);
    lv_obj_set_y(ui_PercentLabel4, 64);
    lv_obj_set_align(ui_PercentLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PercentLabel4, "20%");
    lv_obj_set_style_text_color(ui_PercentLabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PercentLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PercentLabel4, &ui_font_MO16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PercentLabel5 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_PercentLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentLabel5, -181);
    lv_obj_set_y(ui_PercentLabel5, 107);
    lv_obj_set_align(ui_PercentLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PercentLabel5, "0%");
    lv_obj_set_style_text_color(ui_PercentLabel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PercentLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PercentLabel5, &ui_font_MO16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedLabel1 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_SpeedLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLabel1, -38);
    lv_obj_set_y(ui_SpeedLabel1, 0);
    lv_obj_set_align(ui_SpeedLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedLabel1, "");
    lv_obj_set_style_text_color(ui_SpeedLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedLabel1, &ui_font_M050, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATTRIBUTE_1 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATTRIBUTE_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATTRIBUTE_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATTRIBUTE_1, 101);
    lv_obj_set_y(ui_ATTRIBUTE_1, -133);
    lv_obj_set_align(ui_ATTRIBUTE_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATTRIBUTE_1, "ATTRIBUTE STATUS");
    lv_obj_set_style_text_color(ui_ATTRIBUTE_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATTRIBUTE_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ATTRIBUTE_1, &ui_font_MOKO210, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATTRIBUTE1 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATTRIBUTE1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATTRIBUTE1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATTRIBUTE1, 38);
    lv_obj_set_y(ui_ATTRIBUTE1, -100);
    lv_obj_set_align(ui_ATTRIBUTE1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATTRIBUTE1, "Voltage");
    lv_obj_set_style_text_color(ui_ATTRIBUTE1, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATTRIBUTE1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATT1 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATT1, 92);
    lv_obj_set_y(ui_ATT1, -76);
    lv_obj_set_align(ui_ATT1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATT1, "V");
    lv_obj_set_style_text_color(ui_ATT1, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATT1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ATT1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATTRIBUTE_2 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATTRIBUTE_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATTRIBUTE_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATTRIBUTE_2, 155);
    lv_obj_set_y(ui_ATTRIBUTE_2, -54);
    lv_obj_set_align(ui_ATTRIBUTE_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATTRIBUTE_2, "");
    lv_obj_set_style_text_color(ui_ATTRIBUTE_2, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATTRIBUTE_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATT2 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATT2, 214);
    lv_obj_set_y(ui_ATT2, -27);
    lv_obj_set_align(ui_ATT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATT2, "");
    lv_obj_set_style_text_color(ui_ATT2, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATT2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATTRIBUTE3 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATTRIBUTE3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATTRIBUTE3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATTRIBUTE3, 42);
    lv_obj_set_y(ui_ATTRIBUTE3, -5);
    lv_obj_set_align(ui_ATTRIBUTE3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATTRIBUTE3, "Current");
    lv_obj_set_style_text_color(ui_ATTRIBUTE3, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATTRIBUTE3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATT3 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATT3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATT3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATT3, 88);
    lv_obj_set_y(ui_ATT3, 17);
    lv_obj_set_align(ui_ATT3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATT3, "A");
    lv_obj_set_style_text_color(ui_ATT3, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATT3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATTRIBUTE4 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATTRIBUTE4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATTRIBUTE4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATTRIBUTE4, 159);
    lv_obj_set_y(ui_ATTRIBUTE4, -5);
    lv_obj_set_align(ui_ATTRIBUTE4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATTRIBUTE4, "Power");
    lv_obj_set_style_text_color(ui_ATTRIBUTE4, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATTRIBUTE4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATT4 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATT4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATT4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATT4, 214);
    lv_obj_set_y(ui_ATT4, 20);
    lv_obj_set_align(ui_ATT4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATT4, "W");
    lv_obj_set_style_text_color(ui_ATT4, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATT4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATTRIBUTE5 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATTRIBUTE5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATTRIBUTE5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATTRIBUTE5, 48);
    lv_obj_set_y(ui_ATTRIBUTE5, 48);
    lv_obj_set_align(ui_ATTRIBUTE5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATTRIBUTE5, "Eco-Mode");
    lv_obj_set_style_text_color(ui_ATTRIBUTE5, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATTRIBUTE5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATT5 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_ATT5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATT5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ATT5, 91);
    lv_obj_set_y(ui_ATT5, 76);
    lv_obj_set_align(ui_ATT5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATT5, "Km");
    lv_obj_set_style_text_color(ui_ATT5, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATT5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSM = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_LabelSM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSM, 168);
    lv_obj_set_y(ui_LabelSM, 49);
    lv_obj_set_align(ui_LabelSM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSM, "Sports-Mode");
    lv_obj_set_style_text_color(ui_LabelSM, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSMM = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_LabelSMM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSMM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSMM, 220);
    lv_obj_set_y(ui_LabelSMM, 77);
    lv_obj_set_align(ui_LabelSMM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSMM, "Km");
    lv_obj_set_style_text_color(ui_LabelSMM, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSMM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAM = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_LabelAM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAM, 48);
    lv_obj_set_y(ui_LabelAM, -53);
    lv_obj_set_align(ui_LabelAM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAM, "Amp-Hour");
    lv_obj_set_style_text_color(ui_LabelAM, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 169);
    lv_obj_set_y(ui_Label1, -54);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Watt-Hour");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAH = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_LabelAH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAH, 91);
    lv_obj_set_y(ui_LabelAH, -25);
    lv_obj_set_align(ui_LabelAH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAH, "AH");
    lv_obj_set_style_text_color(ui_LabelAH, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAH, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWH = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_LabelWH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWH, 212);
    lv_obj_set_y(ui_LabelWH, -22);
    lv_obj_set_align(ui_LabelWH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWH, "WH");
    lv_obj_set_style_text_color(ui_LabelWH, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWH, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSOC = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_LabelSOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSOC, 146);
    lv_obj_set_y(ui_LabelSOC, -101);
    lv_obj_set_align(ui_LabelSOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSOC, "SOC");
    lv_obj_set_style_text_color(ui_LabelSOC, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSOC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPercent = lv_label_create(ui_Label_speed);
    lv_obj_set_width(ui_LabelPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPercent, 212);
    lv_obj_set_y(ui_LabelPercent, -77);
    lv_obj_set_align(ui_LabelPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPercent, "%");
    lv_obj_set_style_text_color(ui_LabelPercent, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
